version: '3.1'

services:
  nursing-db:
    container_name: postgresql-nursing
    image: postgres:15.1
    environment:
      POSTGRES_DB: nursing-db
      POSTGRES_USER: nursing-postgres-user
      POSTGRES_PASSWORD: nursing-postgres-pwd
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: /home/akio/Db/postgresql
        target: /var/lib/postgres
    networks:
      - postgres-compose-network
      
  nursing-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "mnishimori@yahoo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "developer"
    ports:
      - "16543:80"
    volumes:
      - type: bind
        source: /home/akio/Db/postgresql
        target: /var/lib/postgres
    depends_on:
      - nursing-db
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge