spring:
  jpa:
    show-sql: true
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${NURSINGCALCULATOR_POSTGRES_URL}
    username: nursing-postgres-user
    password: nursing-postgres-pwd
  flyway:
    baseline-on-migrate: true
    schemas: 'flyway'
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

server:
  port: 8080
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${NURSINGCALCULATOR_API_SECURITY_TOKEN_SECRET}